services:
  ncc-line-chatbot-prod:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./data:/bot/data
    ports:
      - 127.0.0.1:3300:3300
    command: /bin/bash -c "source ~/.bashrc && rye run uvicorn rule:app --reload --host=0.0.0.0 --port=3300"