[project]
name = "ncc-line-chatbot-poc"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "k0tk267", email = "k0tk2670@gmail.com" }
]
dependencies = []
readme = "README.md"
requires-python = ">= 3.8"

[project.scripts]
hello = "ncc-line-chatbot-poc:hello"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/ncc_line_chatbot_poc"]
